### ISSUE TITLE
Labs site responsivness

### ISSUE THREAD

**Issue by RolandRP** [RolandRP/DTILabs#90]
p and h1 paddings seem broken enough 
![muitobroken](https://user-images.githubusercontent.com/12788691/27256189-88866476-53b6-11e7-86dd-dd856e092e27.png)

**Comment by KristjanVeensalu** [comment]
Wtf.. kill me

**Comment by KristjanVeensalu** [comment]
Mul on korras kõikide resode peal.

**Comment by RolandRP** [comment]
Vaatame esmasp. ule. Akki mul mingi imearvuti that can break everything.
